# Generated by Django 5.0.1 on 2024-01-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='averange',
            new_name='average',
        ),
    ]
