# Generated by Django 5.0.1 on 2024-02-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by_admin',
            field=models.BooleanField(blank=True, default=True, verbose_name='Creado por Admin'),
        ),
    ]
